### ISSUE TITLE
Support for mac

### ISSUE THREAD

**Issue by mhle** [sandeepmistry/node-bluetooth-hci-socket#12]
Are you planning to support Mac as well in the future? OS X el capital currently doesn't support more than 6 connected devices maybe using this lib can resolve that issue?

**Comment by sandeepmistry** [comment]
@mhle no plans to add support.

However, it is possible to use it if you build from source. Then you have to unload the built-in OS X driver for the adapter, so that's a big drag.

**Comment by alexsuse** [comment]
Any chance you can provide a bit more context on how to "build from source"? I assume you just need to compile the cpp files, but given that the package seems to bind those calls in js, it might be a bit more complicated.

**Comment by sandeepmistry** [comment]
@alexsuse you just need `node-usb` actually - the native bindings are not used at all.
