### ISSUE TITLE
On Linux use D-Bus GATT APIs

### ISSUE THREAD

**Issue by Vudentz** [sandeepmistry/node-bluetooth-hci-socket#27]
Lets please not alienate the Linux upstream, we do have a very complete set of APIs for BLE including GATT, which is build with a LGPL C library and D-Bus APIs so you don't need to rewrite everything from scratch. It is actually in use in Chrome OS as well so I wonder how much code can be shared.

**Comment by sandeepmistry** [comment]
@Vudentz both noble and bleno have been running on Linux prior to the BlueZ 5 release. This makes the out of the box experience much easier for distros that still ship with BlueZ 4.

I'd still like to continue to support the HCI socket binding, as from what I understand the D-Bus API is still experimental and not enable in bluetoothd by default. (Maybe this is no longer correct?)

Anyways, let's continue to discuss adding support for the D-Bus API in:
 * https://github.com/sandeepmistry/noble/issues/310
 * https://github.com/sandeepmistry/bleno/issues/24
