### ISSUE TITLE
Cant install on Beaglebone Black

### ISSUE THREAD

**Issue by MarinRadmilovic** [sandeepmistry/node-bluetooth-hci-socket#28]
I installed all prerequisites for noble package, and this package is its dependency. I can't install this package and the usb adapter is working fine with hcitool. 

> node-gyp rebuild

make: Entering directory `/var/lib/cloud9/BluetoothWeb/node_modules/noble/node_modules/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../node_modules/nan/nan.h:330:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
make: *** [Release/obj.target/binding/src/BluetoothHciSocket.o] Error 1
make: Leaving directory `/var/lib/cloud9/BluetoothWeb/node_modules/noble/node_modules/bluetooth-hci-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.8.13-bone70
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/lib/cloud9/BluetoothWeb/node_modules/noble/node_modules/bluetooth-hci-socket
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"

I tried everything but it's not working yet! Please help

**Comment by sandeepmistry** [comment]
@MarinRadmilovic as per https://github.com/nodejs/nan/issues/414 and https://github.com/nodejs/nan/issues/394 I suggest you upgrade your version of Node.js and/or npm.
