### ISSUE TITLE
nam install graceful-fs

### ISSUE THREAD

**Issue by TomasPangzi** [sandeepmistry/node-bluetooth-hci-socket#29]
common i use: npm install --save-dev graceful-fs
result:
npm WARN optional Skipping failed optional dependency /noble/bluetooth-hci-socket:
npm WARN notsup Not compatible with your operating system or architecture: bluetooth-hci-socket@0.4.4

**Comment by sandeepmistry** [comment]
@TomasPangzi i think this is related to https://github.com/sandeepmistry/noble/issues/414 which you've closed, so I am closing it.
