### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mz92341** [sandeepmistry/node-bluetooth-hci-socket#43]
Hello,

I'm not sure if I have installed correctly node-bluetooth-hci-socket as some warnings pop up. I've visualized the following when I installed it:
 
![image](https://cloud.githubusercontent.com/assets/22983545/19618082/5573bf4c-9841-11e6-8f01-470fdc32e8a1.png)

Could anyone help me out?

Thanks

**Comment by sandeepmistry** [comment]
Hi @mz92341,

Looks ok to me. `xpc-connection` is an optional dependency and needed on OS X only. The `package.json` error looks like it's because you don't have a package.json in your home folder.
