### ISSUE TITLE
Node-red issue

### ISSUE THREAD

**Issue by RGCairns** [sandeepmistry/node-bluetooth-hci-socket#44]
![command](https://cloud.githubusercontent.com/assets/22314945/19765346/bccda804-9c3f-11e6-86fa-2a78a5e7ac27.png)

Hi,
I've been trying to download and install this node for a while now.
When it comes to running node-red the package is ackowledged but never loads.
Any help would be greatly appreciated

Thanks

**Comment by sandeepmistry** [comment]
Hi @RGCairns,

Please see the links in the prerequisites: https://github.com/sandeepmistry/node-bluetooth-hci-socket#prerequisites

Also you mind find @don's youtube video is helpful: https://www.youtube.com/watch?v=mL9B8wuEdms
