### ISSUE TITLE
Compiling for MIPS architecture. 

### ISSUE THREAD

**Issue by cseiber** [sandeepmistry/node-bluetooth-hci-socket#61]
Good evening, I am attempting to use this library within a small embedded system. I am getting an error with the binding.node file found in the path "bluetooth-hci-socket/build/Release/binding.node", oddly enough however, on your repository here I do not see the build folder. This is part of a larger npm install of the node rolling spider library. The error I am getting is that it says the binding.node file stated in the above path "is not an ELF executable for MIPS". Sorry for putting this as an issue but I wasn't sure of another way to contact you. Any chance you know how I can compile this to work on a MIPS based architecture? 

Thank you!

**Comment by sandeepmistry** [comment]
@cseiber if you follow https://github.com/nodejs/node-gyp#installation

on your MIPS device that should be all you need, then run `node-gyp rebuild` in the `bluetooth-hci-socket` folder.
