### ISSUE TITLE
Turning on bluetooth after installing WinUSB

### ISSUE THREAD

**Issue by eohan** [sandeepmistry/node-bluetooth-hci-socket#62]
Hi, 
I installed the WINUSB driver for my Intel Wireless Bluetooth 7260 bluetooth hardware. However, I'm not able to enable or disable bluetooth with the WINUSB driver. The default apps to enable bluetooth do not work anymore. Running a bluetooth code using this just hangs
```
set BLUETOOTH_HCI_SOCKET_USB_VID=0x050d
set BLUETOOTH_HCI_SOCKET_USB_PID=0x065a

node <file>.js
```
I'm running on Windows 8.1

**Comment by sandeepmistry** [comment]
With WinUSB you won't be able to enable or disable Bluetooth using the Windows UI as the driver is unloaded.

See https://github.com/sandeepmistry/node-bluetooth-hci-socket#windows to see how to revert the driver.
