### ISSUE TITLE
Intel(R) Dual Band Wireless-AC 8260

### ISSUE THREAD

**Issue by T-Rez-Mity** [sandeepmistry/node-bluetooth-hci-socket#63]
I'm trying to make this work with my laptop which has a Intel(R) Dual Band Wireless-AC 8260 chipset. Should I just give up as I see this is not one of the compatible devices or is there something I could try?  

It looks like you may have allowed for some bending of the "rules" with this: 
Example for USB device id: 050d:065a:

set BLUETOOTH_HCI_SOCKET_USB_VID=0x050d
set BLUETOOTH_HCI_SOCKET_USB_PID=0x065a

node <file>.js

If I were to replace the Example with: 

set BLUETOOTH_HCI_SOCKET_USB_VID=0x8087
set BLUETOOTH_HCI_SOCKET_USB_PID=0x0a2a

node forceFit.js
perhaps it would work..

**Comment by sandeepmistry** [comment]
@T-Rez-Mity yep, try it out :)

If that works, please submit a PR like: https://github.com/sandeepmistry/node-bluetooth-hci-socket/pull/31

Note: you'll also have to swap out the driver with WinUSB: https://github.com/sandeepmistry/node-bluetooth-hci-socket#windows
