### ISSUE TITLE
node-bluetooth-hci-socket not support macOS?

### ISSUE THREAD

**Issue by buitronghieu** [sandeepmistry/node-bluetooth-hci-socket#67]
I see not support macOS Darwin?
![image](https://cloud.githubusercontent.com/assets/6505403/25794446/20e2bcf0-33fb-11e7-8d5f-8f294e24031b.png)

**Comment by sandeepmistry** [comment]
@buitronghieu that's correct. macOS/darwin does not have a concept of Bluetooth HCI sockets.

This module can be manually installed on macOS darwin and use USB Bluetooth adapters directly once the driver has been removed.

**Comment by kefayati** [comment]
@sandeepmistry so exactly how to install _manually_?
