### ISSUE TITLE
Why not support OSX darwin?

### ISSUE THREAD

**Issue by buitronghieu** [sandeepmistry/node-bluetooth-hci-socket#70]
I see write document support OSX, but when installed, does not support?
<img width="582" alt="nh ch p man hinh 2017-06-12 luc 09 59 29" src="https://user-images.githubusercontent.com/6505403/27017875-173f7690-4f56-11e7-9512-bfa51fd8940b.png">

**Comment by sandeepmistry** [comment]
@buitronghieu please see the read me: https://github.com/sandeepmistry/node-bluetooth-hci-socket#node-bluetooth-hci-socket

OS X is only supported and experiment if you manually clone the repo and install node-usb.
