### ISSUE TITLE
unable to run le-scan example after node-gyp rebuild

### ISSUE THREAD

**Issue by GuidoS** [sandeepmistry/node-bluetooth-hci-socket#71]
I wanted to try out bleno, but found this package causing issues.

I am on a raspberry pi zero w running node lts/baron v6.11.3

> \> sudo node examples/le-scan-test.js
> module.js:434
>   return process.dlopen(module, path._makeLong(filename));
>                  ^
> 
> Error: Module version mismatch. Expected 46, got 48.
>     at Error (native)
>     at Object.Module._extensions..node (module.js:434:18)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/home/pi/git/guidos/sandbox/raspberrypi/blinky/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)

Any thoughts on how I can get this working of if there is something I am doing incorrectly?

**Comment by sandeepmistry** [comment]
Rebuild the module using `node-gyp rebuild` or delete installed module and re-install using npm to rebuild.
