### ISSUE TITLE
Is it possible to use usb bluetooth adapter without Zagdig?

### ISSUE THREAD

**Issue by Arteha** [sandeepmistry/node-bluetooth-hci-socket#89]

**Comment by ghost** [comment]
I assume you mean on Windows.  If you're using windows < 10 then the answer is a definitive no. If you're using windows, 10 then you can potentially use the external noble-uwp library bindings. I don't know what the current state of that library is though.

**Comment by Arteha** [comment]
Thank you.
The best solution is: NodeRT(`https://github.com/NodeRT/NodeRT`) or WinJS.
Windows.Devices.Bluetooth `https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/bluetooth`
